name: "read-out"
services:
  server:
    build:
      context: .
    environment:
      - SERVER_ENGINE=kokoro
      - SERVER_VOICE=af
      - SERVER_CUDA=1
    ports:
      - 5000:5000
    volumes:
      - ./engines/kokoro/model:/model:ro
      - hf_cache:/root/.cache/huggingface
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  hf_cache:
