services:
  tts:
    build:
      context: .
      args:
        MODEL_NAME: tts_models/multilingual/multi-dataset/xtts_v2
    volumes:
      - ./.cache/local:/root/.local/share
    ports:
      - 5002:5002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
